replicaCount: 1
image:
  repository: maybetuandat/vdt_fe
  pullPolicy: IfNotPresent
  tag: "2.4"

securityContext: {}

# service:
#   type: ClusterIP 
#   port: 80
#   targetPort: 80
#   portName: vdt-web-port

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30001
  portName: vdt-web-port

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: vdt-app.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: vdt-tls-secret
      hosts:
        - vdt-app.local

resources: {}

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}