replicaCount: 1
image:
  repository: maybetuandat/vdt_fe
  pullPolicy: IfNotPresent
  tag: "1.0"

securityContext: {}

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30001
  portName: vdt-web-port


resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "200m"

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}